### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/inferno-loadable/lib/index.js:3

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [kurdin/inferno-loadable#2]

**Comment by sprlwrksAprilmintacpineda** [comment]
https://github.com/infernojs/inferno/issues/1356

**Comment by kurdin** [comment]
This is your webpack configuration problem not inferno.

**Comment by sprlwrksAprilmintacpineda** [comment]
@kurdin I have no webpack configuration files. I thought the whole point of using these tools is to abstract that away.

**Comment by SupremeTechnopriest** [comment]
Im hitting this bug too.  Using `create-inferno-app`.  Are you not transforming import statements?

**Comment by SupremeTechnopriest** [comment]
Just checked and it LGTM.  Gonna look into this.
